CREATE TABLE Cad_Composto (
    ID_COMPOSTO     INT             NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COMPOSTO        INT             NOT NULL,
    DESC_COMPOSTO   VARCHAR(150)    NOT NULL,
    BPCS            VARCHAR(20)     NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
