CREATE TABLE Cad_Metodo_Avaliacao (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESC_METODO VARCHAR(50) NOT NULL,
    SETOR VARCHAR(50) NULL,
    UNIQUE KEY UNQ_DESC_METODO (DESC_METODO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
