CREATE TABLE Cad_Controle_Processo (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESC_CONTROLE VARCHAR(255) NOT NULL,
    METODO_AVALIACAO VARCHAR(50),
    PREVENT_DETECT VARCHAR(10),
    SETOR VARCHAR(50),
    CONSTRAINT FK_Cad_Controle_Processo_Cad_Metodo_Avaliacao FOREIGN KEY (METODO_AVALIACAO) REFERENCES Cad_Metodo_Avaliacao (DESC_METODO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
