CREATE TABLE Cad_Projeto (
    ID_PROJETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PROJETO VARCHAR(50) NOT NULL,
    PRO_OEM VARCHAR(50),
    UNIQUE KEY UNQ_PROJETO (PROJETO),
    CONSTRAINT FK_Cad_Projeto_Cad_Oem FOREIGN KEY(PRO_OEM) REFERENCES Cad_Oem(OEM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
