CREATE TABLE Cad_Material (
    ID_MATERIAL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MATERIAL INT NOT NULL,
    DESC_MATERIAL VARCHAR(255) NULL,
    MAT_LINHA VARCHAR(50) NULL,
    MAT_PROJETO VARCHAR(50) NULL,
    N_DESENHO VARCHAR(100) NULL,
    N_PLANO VARCHAR(50) NULL,
    BPCS VARCHAR(10) NULL,
    META VARCHAR(10) NULL,
    OBSERVACAO VARCHAR(500) NULL,
    IMAGE VARCHAR(150) NULL,
    IMAGEROD VARCHAR(255) NULL,
    CONSTRAINT FK_Cad_Material_Cad_Linha FOREIGN KEY(MAT_LINHA) REFERENCES Cad_Linha(LINHA),
    CONSTRAINT FK_Cad_Material_Cad_Projeto FOREIGN KEY(MAT_PROJETO) REFERENCES Cad_Projeto(PROJETO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
