CREATE TABLE Causas (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESC_CAUSA VARCHAR(255) NULL,
    ID_PROBLEMA_ID INT NULL,
    CONSTRAINT Causas_ID_PROBLEMA_ID FOREIGN KEY (ID_PROBLEMA_ID) REFERENCES Problemas (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
