CREATE TABLE Cad_Usuario (
    PK_ID       INT NOT NULL AUTO_INCREMENT,
    NOME        VARCHAR(100) NOT NULL, -- DDZL4=L04;DDZL6=L06;DDZL7=L07;DDZL8=L08;DDZL9=L09;DDZL11=L11;DDZL12=L12;DDZL17=L17;DDZL19=L19;DDZL27=L27;DDZL26=L26;DDZL28=L28;
    LOGIN       VARCHAR(50) NOT NULL,
    SENHA       VARCHAR(50) NOT NULL,
    SETOR       VARCHAR(50),
    SOBRE_NOME  VARCHAR(80),
    PLANTA      VARCHAR(50), -- Varginha, Atibaia
    EMAIL       VARCHAR(255),
    PRIMARY KEY (PK_ID),
    UNIQUE KEY UNQ_LOGIN (LOGIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Cad_Usuario (NOME, LOGIN, SENHA, PLANTA) VALUES ('DDZL4', 'admin', 'admin', 'Varginha');
