CREATE TABLE Cad_UnidadeFQ (
    ID_UNIDADE_FREQUENCIA 	INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UNIDADE_FREQUENCIA 		VARCHAR(50) NOT NULL,
    SETOR 					VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
