CREATE TABLE DDZ_Controle (
    ID INT NOT NULL PRIMARY KEY,
    MATERIAL VARCHAR(255) NOT NULL,
    DATA_BASE DATE NOT NULL,
    LINHA VARCHAR(255) NOT NULL,
    SCRAP_TOTAL DECIMAL(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
