CREATE TABLE CAD_FUNCAO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CAD_FUNCAO_PARAMETRO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODIGO INT NULL,
    PARAMETRO VARCHAR(255) NOT NULL,
    VALOR_PADRAO VARCHAR(255) NOT NULL,
    CONTEXTO VARCHAR(4000) NOT NULL,
    ID_CAD_FUNCAO INT NOT NULL,
    CONSTRAINT FK_CADFUNC_CADFUNCPAR FOREIGN KEY (ID_CAD_FUNCAO) REFERENCES CAD_FUNCAO(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CAD_FUNCAO_PARAM_ESTAB (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ESTABELECIMENTO VARCHAR(255) NOT NULL,
    VALOR VARCHAR(255) NOT NULL,
    ID_CAD_FUNC_PARAM INT NOT NULL,
    CONSTRAINT FK_CADFUNCPAR_FNCPAREST FOREIGN KEY (ID_CAD_FUNC_PARAM) REFERENCES CAD_FUNCAO_PARAMETRO(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CAD_FUNCAO_PARAM_PERFIL (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PERFIL VARCHAR(255) NOT NULL,
    VALOR VARCHAR(255) NOT NULL,
    ID_CAD_FUNC_PARAM INT NOT NULL,
    CONSTRAINT FK_CADFUNCPAR_FNCPARPER FOREIGN KEY (ID_CAD_FUNC_PARAM) REFERENCES CAD_FUNCAO_PARAMETRO(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CAD_FUNCAO_PARAM_USUARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(255) NOT NULL,
    VALOR VARCHAR(255) NOT NULL,
    ID_CAD_FUNC_PARAM INT NOT NULL,
    CONSTRAINT FK_CADFUNCPAR_FNCPARUSR FOREIGN KEY (ID_CAD_FUNC_PARAM) REFERENCES CAD_FUNCAO_PARAMETRO(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
