CREATE TABLE Aderencia (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ADERENCIA FLOAT NULL,
    DATA_INPUT VARCHAR(10) NULL,
    LINHA VARCHAR(50) NULL,
    META FLOAT NULL,
    TIPO CHAR(1) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
