
package com.cooperstandard.views.acabamento;

import com.cooperstandard.views.principal.AguardeGerandoRelatório;
import com.cooperstandard.model.ModelOperacao;
import com.cooperstandard.util.EstiloTablaRenderer;
import com.cooperstandard.util.HeaderRenderer;
import com.cooperstandard.controller.acabamento.ControllerOperacao;
import java.sql.Connection;
import com.cooperstandard.dbs.ConexaoSql;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rsouza10
 */
public class ViewOperacaoAc extends javax.swing.JFrame {

    ModelOperacao modelOperacao = new ModelOperacao();
    ControllerOperacao controllerOperacao = new ControllerOperacao();
    ArrayList<ModelOperacao> listaModelOperacao = new ArrayList<ModelOperacao>();
    String tipoCadastro;
    private JFrame solicitante = null;

    public ViewOperacaoAc() {
        initComponents();
        carregaOperacao();
        carregaOperacaoConsulta();
        tbOperacaoPesquisar.getTableHeader().setDefaultRenderer(new HeaderRenderer(tbOperacaoPesquisar));
        tbOperacaoPesquisar.setDefaultRenderer(Integer.class, new EstiloTablaRenderer());
        tbOperacaoPesquisar.setDefaultRenderer(String.class, new EstiloTablaRenderer());
        tbOperacao.getTableHeader().setDefaultRenderer(new HeaderRenderer(tbOperacao));
        tbOperacao.setDefaultRenderer(Integer.class, new EstiloTablaRenderer());
        tbOperacao.setDefaultRenderer(String.class, new EstiloTablaRenderer());
    }

    public ViewOperacaoAc(JFrame frame) {
        initComponents();
        carregaOperacao();
        carregaOperacaoConsulta();
        solicitante = frame;
        tbOperacaoPesquisar.getTableHeader().setDefaultRenderer(new HeaderRenderer(tbOperacaoPesquisar));
        tbOperacaoPesquisar.setDefaultRenderer(Integer.class, new EstiloTablaRenderer());
        tbOperacaoPesquisar.setDefaultRenderer(String.class, new EstiloTablaRenderer());
        tbOperacao.getTableHeader().setDefaultRenderer(new HeaderRenderer(tbOperacao));
        tbOperacao.setDefaultRenderer(Integer.class, new EstiloTablaRenderer());
        tbOperacao.setDefaultRenderer(String.class, new EstiloTablaRenderer());
    }

    public void setSolicitante(JFrame solicitante) {
        this.solicitante = solicitante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOperacaoPesquisar = new javax.swing.JTable();
        txtBusca = new javax.swing.JTextField();
        lbBusca1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnNovo1 = new javax.swing.JButton();
        btnAlterar1 = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        lbBuscar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbOrdem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescOp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbSetor = new javax.swing.JComboBox<>();
        lbCod = new javax.swing.JLabel();
        cbClassificacao = new javax.swing.JComboBox<>();
        txtFornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPreparadoPor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEquipe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdtData = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lbId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCodOp = new javax.swing.JFormattedTextField();
        txtOrdem = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbOperacao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Operação");

        tbOperacaoPesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ordem", "Cod_Operação", "Desc. Operação", "Classificação", "Fornecedor", "Preparado Por", "Telefone", "Responsável", "Equipe", "Data de Criação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbOperacaoPesquisar.setFocusable(false);
        tbOperacaoPesquisar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbOperacaoPesquisar);
        if (tbOperacaoPesquisar.getColumnModel().getColumnCount() > 0) {
            tbOperacaoPesquisar.getColumnModel().getColumn(0).setMinWidth(0);
            tbOperacaoPesquisar.getColumnModel().getColumn(0).setMaxWidth(0);
            tbOperacaoPesquisar.getColumnModel().getColumn(1).setMinWidth(100);
            tbOperacaoPesquisar.getColumnModel().getColumn(1).setMaxWidth(100);
            tbOperacaoPesquisar.getColumnModel().getColumn(3).setMinWidth(200);
        }

        txtBusca.setBackground(new java.awt.Color(255, 255, 204));
        txtBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        lbBusca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBusca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-binóculos-filled-50.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-pdf-2-filled-50.png"))); // NOI18N
        jButton1.setText("Visualizar/Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNovo1.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-joyent-filled-20 (1).png"))); // NOI18N
        btnNovo1.setText("Novo");
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });

        btnAlterar1.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-editar-filled-50.png"))); // NOI18N
        btnAlterar1.setText("Alterar");
        btnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar1ActionPerformed(evt);
            }
        });

        btnExcluir1.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-excluir-filled-50.png"))); // NOI18N
        btnExcluir1.setText("Excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        btnLimpar1.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-n¦o-perturbe-filled-50.png"))); // NOI18N
        btnLimpar1.setText("Cancelar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });

        lbBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbBuscar.setText("Buscar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1209, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnLimpar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbBuscar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBuscar)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBusca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBusca1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar1)
                    .addComponent(btnExcluir1)
                    .addComponent(btnAlterar1)
                    .addComponent(btnNovo1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pesquisar", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbOrdem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbOrdem.setText("Ordem:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Desc. Operação:");

        txtDescOp.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Setor:");

        cbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acabamento" }));
        cbSetor.setEnabled(false);
        cbSetor.setFocusable(false);

        lbCod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCod.setText("Cod_Op:");

        cbClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Crítico", "Crítico", "Crítico + Segurança" }));
        cbClassificacao.setEnabled(false);

        txtFornecedor.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Classificação:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Fornecedor:");

        txtPreparadoPor.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Preparado Por:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefone:");

        txtResponsavel.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Responsável do Processo:");

        txtEquipe.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Equipe:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cliente:");

        jdtData.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Data:");

        txtCliente.setEnabled(false);

        lbId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbId.setText("Código:");

        txtId.setEnabled(false);

        txtTelefone.setEnabled(false);

        txtCodOp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        txtCodOp.setEnabled(false);

        txtOrdem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        txtOrdem.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbOrdem)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtOrdem)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCod)
                            .addComponent(txtCodOp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescOp, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPreparadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jdtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtDescOp))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbId)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSetor)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbOrdem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCodOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbCod))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPreparadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFornecedor)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-salvar-filled-50.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 20/icons8-n¦o-perturbe-filled-50.png"))); // NOI18N
        btnLimpar.setText("Cancelar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tbOperacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ordem", "Cod_Operação", "Desc.Operação", "Classificação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbOperacao.setFocusable(false);
        tbOperacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbOperacao);
        if (tbOperacao.getColumnModel().getColumnCount() > 0) {
            tbOperacao.getColumnModel().getColumn(0).setMinWidth(120);
            tbOperacao.getColumnModel().getColumn(0).setMaxWidth(120);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastrar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (tipoCadastro.equals("novo")) {
            if (txtOrdem.getText().equals("") || txtCodOp.getText().equals("") || txtDescOp.getText().equals("") || cbClassificacao.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Campo obrigatório!", "ERRO", JOptionPane.WARNING_MESSAGE);
            } else {
                salvarOperacao();
            }
        } else if (tipoCadastro.equals("alteracao")) {
            if (txtOrdem.getText().equals("") || txtCodOp.getText().equals("") || txtDescOp.getText().equals("") || cbClassificacao.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Campo obrigatório!", "ERRO", JOptionPane.WARNING_MESSAGE);
            } else {
                alterarOperacao();
                btnSalvar.setEnabled(false);
                jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() - 1);
            }

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.desabilitarCampos();
        limparDados();
        btnSalvar.setEnabled(false);
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() - 1);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased

        DefaultTableModel tabela = (DefaultTableModel) this.tbOperacaoPesquisar.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<>(tabela);
        this.tbOperacaoPesquisar.setRowSorter(sorter);
        String text = txtBusca.getText();
        sorter.setRowFilter(RowFilter.regexFilter(text, 3, 4));

    }//GEN-LAST:event_txtBuscaKeyReleased

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        novoProjeto();
        btnSalvar.setEnabled(true);
        habilitarCampos();
        txtOrdem.requestFocus();
        tipoCadastro = "novo";
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() + 1);
    }//GEN-LAST:event_btnNovo1ActionPerformed

    private void btnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar1ActionPerformed
        int linhasselecionada = tbOperacaoPesquisar.getSelectedRow();

        if (linhasselecionada < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um item antes de clicar no botão!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            novoProjeto();
            btnSalvar.setEnabled(true);
            habilitarCampos();
            recuperarOperacao();
            tipoCadastro = "alteracao";
            jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() + 1);
        }
    }//GEN-LAST:event_btnAlterar1ActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        int linhasselecionada = tbOperacaoPesquisar.getSelectedRow();

        if (linhasselecionada < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um item antes de clicar no botão!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            this.excluirOperacao();
            limparDados();
        }
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        limparDadosPesquisa();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 final AguardeGerandoRelatório carregando = new AguardeGerandoRelatório();
            carregando.setVisible(true);
            Thread t = new Thread() {
                public void run() {
                    try {
                        String logo = "/images/logocooper.jpg";
                        
                        Connection con = new ConexaoSql().getCon();
                        Map p = new HashMap();
                        p.put("logo", this.getClass().getResourceAsStream(logo));
                        JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getResource("/Relatorios/listagemoperacaoAC.jasper"));

                        JasperPrint print = JasperFillManager.fillReport(jr, p, con);
                        JasperViewer view = new JasperViewer(print, false);
                        view.setTitle("Operações");

                        view.setVisible(true);
                    } catch (Exception erro) {

                        JOptionPane.showMessageDialog(null, "deu erro =" + erro);
                        System.out.println(erro);

                    }
                    carregando.dispose();
                }
            };
            t.start();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void excluirOperacao() {
        int linha = tbOperacaoPesquisar.getSelectedRow();
        String nome = (String) tbOperacaoPesquisar.getValueAt(linha, 3);
        int codigo = (Integer) tbOperacaoPesquisar.getValueAt(linha, 0);
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                + " excluir o registro \nNome: "
                + nome + " ?", "Atenção", JOptionPane.YES_OPTION);

        if (opcao == JOptionPane.OK_OPTION) {
            if (controllerOperacao.excluirOperacaoAcController(codigo)) {
                JOptionPane.showMessageDialog(this, "Registro excluido com sucesso!");
                carregaOperacao();
                carregaOperacaoConsulta();
                if (solicitante != null) {
                    if (solicitante instanceof ViewEquipamentoAc) {
                        ViewEquipamentoAc vp = (ViewEquipamentoAc) solicitante;
                        vp.addItemLista(txtDescOp.getText());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private boolean salvarOperacao() {
        modelOperacao.setOrdem(Integer.parseInt(this.txtOrdem.getText()));
        modelOperacao.setCod_op(Integer.parseInt(this.txtCodOp.getText()));
        modelOperacao.setOperacao(this.txtDescOp.getText());
        modelOperacao.setCod_simbol_op(this.cbClassificacao.getSelectedItem().toString());
        modelOperacao.setOpe_setor(this.cbSetor.getSelectedItem().toString());
        modelOperacao.setFornecedor(this.txtFornecedor.getText());
        modelOperacao.setPreparado_por(this.txtPreparadoPor.getText());
        modelOperacao.setTelefone(this.txtTelefone.getText());
        modelOperacao.setResponsavel_processo(this.txtResponsavel.getText());
        modelOperacao.setEquipe(this.txtEquipe.getText());
        modelOperacao.setCliente(this.txtCliente.getText());
        try {
            modelOperacao.setData_criacao(new SimpleDateFormat("yyyy/MM/dd").format(jdtData.getDate()));

        } catch (Exception ex) {
            Logger.getLogger(ViewOperacaoAc.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (controllerOperacao.salvarOperacaoAcController(modelOperacao) > 0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
            this.desabilitarCampos();
            this.carregaOperacao();
            this.carregaOperacaoConsulta();
            if (solicitante != null) {
                if (solicitante instanceof ViewEquipamentoAc) {
                    ViewEquipamentoAc vp = (ViewEquipamentoAc) solicitante;
                    vp.addItemLista(txtDescOp.getText());
                }
            }
            limparDados();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean recuperarOperacao() {
        int linha = this.tbOperacaoPesquisar.getSelectedRow();
        int codigo = (Integer) tbOperacaoPesquisar.getValueAt(linha, 0);
        try {
            modelOperacao = controllerOperacao.getOperacaoAcController(codigo);
            this.txtId.setText(String.valueOf(modelOperacao.getId_operacao()));
            this.txtOrdem.setText(String.valueOf(modelOperacao.getOrdem()));
            this.txtCodOp.setText(String.valueOf(modelOperacao.getCod_op()));
            this.txtDescOp.setText(modelOperacao.getOperacao());
            this.cbClassificacao.setSelectedItem(modelOperacao.getCod_simbol_op());
            this.cbSetor.setSelectedItem(modelOperacao.getOpe_setor());
            this.txtFornecedor.setText(modelOperacao.getFornecedor());
            this.txtPreparadoPor.setText(modelOperacao.getPreparado_por());
            this.txtTelefone.setText(modelOperacao.getTelefone());
            this.txtResponsavel.setText(modelOperacao.getResponsavel_processo());
            this.txtEquipe.setText(modelOperacao.getEquipe());
            this.txtCliente.setText(modelOperacao.getCliente());
            this.jdtData.setDate(new SimpleDateFormat("yyyy/MM/dd").parse(modelOperacao.getData_criacao()));
            return true;
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    private boolean alterarOperacao() {
        modelOperacao.setId_operacao(Integer.parseInt(this.txtId.getText()));
        modelOperacao.setOrdem(Integer.parseInt(this.txtOrdem.getText()));
        modelOperacao.setCod_op(Integer.parseInt(this.txtCodOp.getText()));
        modelOperacao.setOperacao(this.txtDescOp.getText());
        modelOperacao.setCod_simbol_op(this.cbClassificacao.getSelectedItem().toString());
        modelOperacao.setOpe_setor(this.cbSetor.getSelectedItem().toString());
        modelOperacao.setFornecedor(this.txtFornecedor.getText());
        modelOperacao.setPreparado_por(this.txtPreparadoPor.getText());
        modelOperacao.setTelefone(this.txtTelefone.getText());
        modelOperacao.setResponsavel_processo(this.txtResponsavel.getText());
        modelOperacao.setEquipe(this.txtEquipe.getText());
        try {
            modelOperacao.setData_criacao(new SimpleDateFormat("yyyy/MM/dd").format(jdtData.getDate()));
        } catch (Exception ex) {
            Logger.getLogger(ViewOperacaoAc.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (controllerOperacao.atualizarOperacaoAcController(modelOperacao)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            this.desabilitarCampos();
            this.carregaOperacao();
            if (solicitante != null) {
                if (solicitante instanceof ViewEquipamentoAc) {
                    ViewEquipamentoAc vp = (ViewEquipamentoAc) solicitante;
                    vp.addItemLista(txtDescOp.getText());
                }
            }
            limparDados();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void carregaOperacao() {
        listaModelOperacao = controllerOperacao.getListaOperacaoAcController();
        DefaultTableModel modelo = (DefaultTableModel) tbOperacaoPesquisar.getModel();
        modelo.setNumRows(0);
        int cont = listaModelOperacao.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelOperacao.get(i).getId_operacao(),
                listaModelOperacao.get(i).getOrdem(),
                listaModelOperacao.get(i).getCod_op(),
                listaModelOperacao.get(i).getOperacao(),
                listaModelOperacao.get(i).getCod_simbol_op(),
                listaModelOperacao.get(i).getFornecedor(),
                listaModelOperacao.get(i).getPreparado_por(),
                listaModelOperacao.get(i).getTelefone(),
                listaModelOperacao.get(i).getResponsavel_processo(),
                listaModelOperacao.get(i).getEquipe(),
                listaModelOperacao.get(i).getData_criacao()

            });

        }

    }

    private void carregaOperacaoConsulta() {
        listaModelOperacao = controllerOperacao.getListaOperacaoAcController();
        DefaultTableModel modelo = (DefaultTableModel) tbOperacao.getModel();
        modelo.setNumRows(0);
        int cont = listaModelOperacao.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelOperacao.get(i).getOrdem(),
                listaModelOperacao.get(i).getCod_op(),
                listaModelOperacao.get(i).getOperacao(),
                listaModelOperacao.get(i).getCod_simbol_op()

            });

        }

    }

    public void desabilitarCampos() {
        txtOrdem.setEnabled(false);
        txtOrdem.setEnabled(false);
        txtCodOp.setEnabled(false);
        txtDescOp.setEnabled(false);
        cbClassificacao.setEnabled(false);
        txtFornecedor.setEnabled(false);
        txtPreparadoPor.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtEquipe.setEnabled(false);
        txtCliente.setEnabled(false);
        jdtData.setEnabled(false);
    }

    public void limparDados() {
        txtId.setText("");
        txtOrdem.setText("");
        txtCodOp.setText("");
        txtDescOp.setText("");
        cbClassificacao.setSelectedIndex(-1);
        txtFornecedor.setText("");
        txtPreparadoPor.setText("");
        txtTelefone.setText("");
        txtResponsavel.setText("");
        txtEquipe.setText("");
        txtCliente.setText("");
        jdtData.setDate(null);
        txtBusca.setText("");
    }

    public void limparDadosPesquisa() {
        txtBusca.setText("");
    }

    public void novoProjeto() {
        habilitarCampos();
        txtId.setText("Novo");
        txtOrdem.setText("");
        txtCodOp.setText("");
        txtDescOp.setText("");
        cbClassificacao.setSelectedIndex(-1);
        txtFornecedor.setText("");
        txtPreparadoPor.setText("");
        txtTelefone.setText("");
        txtResponsavel.setText("");
        txtEquipe.setText("");
        txtCliente.setText("");
        jdtData.setDate(null);

    }

    public void habilitarCampos() {
        txtOrdem.setEnabled(true);
        txtCodOp.setEnabled(true);
        txtDescOp.setEnabled(true);
        cbClassificacao.setEnabled(true);
        txtFornecedor.setEnabled(true);
        txtPreparadoPor.setEnabled(true);
        txtTelefone.setEnabled(true);
        txtResponsavel.setEnabled(true);
        txtEquipe.setEnabled(true);
        txtCliente.setEnabled(true);
        jdtData.setEnabled(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOperacaoAc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOperacaoAc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOperacaoAc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOperacaoAc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOperacaoAc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar1;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbClassificacao;
    private javax.swing.JComboBox<String> cbSetor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdtData;
    private javax.swing.JLabel lbBusca1;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbOrdem;
    private javax.swing.JTable tbOperacao;
    private javax.swing.JTable tbOperacaoPesquisar;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtCodOp;
    private javax.swing.JTextField txtDescOp;
    private javax.swing.JTextField txtEquipe;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtId;
    private javax.swing.JFormattedTextField txtOrdem;
    private javax.swing.JTextField txtPreparadoPor;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
